insert into equipment_type (id,name,alias) values (11,'Папка','OTYP_FOLDER');
insert into equipment_type (id,name,alias) values (12,'Филиал электрических сетей','OTYP_FILIAL_ELECTRIC_NETWORK');
insert into equipment_type (id,name,alias) values (13,'Районные электрические сети','OTYP_DISTRICT_ELECTRIC_NETWORK');
insert into equipment_type (id,name,alias) values (14,'Группа подстанций','OTYP_DBTREE_PSGPOUP');
insert into equipment_type (id,name,alias) values (15,'Группа ЛЭП','OTYP_DBTREE_VLGPOUP');
insert into equipment_type (id,name,alias) values (16,'Группа ЛЭП класса напряжения','OTYP_DBTREE_VLGPOUP_UCLS');
insert into equipment_type (id,name,alias) values (17,'Группа ПС класса напряжения','OTYP_DBTREE_PSGPOUP_UCLS');
insert into equipment_type (id,name,alias) values (18,'Подстанция','OTYP_SUBSTATION');
insert into equipment_type (id,name,alias) values (19,'Воздушная ЛЭП','OTYP_AIR_POWER_LINE');
insert into equipment_type (id,name,alias) values (20,'Распределительная ПС','OTYP_DISTRIBUTION_SUBSTATION');
insert into equipment_type (id,name,alias) values (21,'Разъединитель','OTYP_DISCONNECTING_SWITCH');
insert into equipment_type (id,name,alias) values (22,'Выключатель','OTYP_POWER_SWITCH');
insert into equipment_type (id,name,alias) values (23,'Реклоузер','OTYP_RECLOSER');
insert into equipment_type (id,name,alias) values (24,'Трансформатор двухобмоточный','OTYP_TWO_WINDING_TRANSFORMER');
insert into equipment_type (id,name,alias) values (25,'Распределительное устройство','OTYP_DISTRIBUTION');
insert into equipment_type (id,name,alias) values (26,'Секция шин','OTYP_BUS_SECTION');
insert into equipment_type (id,name,alias) values (27,'Кабельная ЛЭП','OTYP_CABLE_POWER_LINE');
insert into equipment_type (id,name,alias) values (28,'Заземляющий нож','OTYP_GROUNDER');
insert into equipment_type (id,name,alias) values (29,'Выключатель с выкатным элементом','OTYP_POWER_SWITCH_WITHDRAWABLE');
insert into equipment_type (id,name,alias) values (30,'Система шин','OTYP_BUS_NETWORK');
insert into equipment_type (id,name,alias) values (31,'Присоединение','OTYP_JOINING');
insert into equipment_type (id,name,alias) values (32,'Предохранитель','OTYP_FUSE');
insert into equipment_type (id,name,alias) values (33,'Двухобмоточный трансформатор собственных нужд','OTYP_AUXILIARY_TRANSFORMER_2W');
insert into equipment_type (id,name,alias) values (34,'Обмотка трансформатора №1','OTYP_TRANSFORMER_WINDING_EDGE1');
insert into equipment_type (id,name,alias) values (35,'Обмотка трансформатора №2','OTYP_TRANSFORMER_WINDING_EDGE2');
insert into equipment_type (id,name,alias) values (36,'Отделитель','OTYP_ISOLATING_SWITCH');
insert into equipment_type (id,name,alias) values (37,'Разъединитель с выкатным элементом','OTYP_DISCONNECTING_SWITCH_WITHDRAWABLE');
insert into equipment_type (id,name,alias) values (38,'Трансформатор трехобмоточный','OTYP_THREE_WINDING_TRANSFORMER');
insert into equipment_type (id,name,alias) values (39,'Обмотка трансформатора №3','OTYP_TRANSFORMER_WINDING_EDGE3');
insert into equipment_type (id,name,alias) values (40,'Устройство регулирования трансформации','OTYP_TRANSFORMER_POWER_CONTROL');
insert into equipment_type (id,name,alias) values (41,'Трансформатор с расщепленной обмоткой НН','OTYP_TWO_WINDING_TRANSFORMER_NN');
insert into equipment_type (id,name,alias) values (42,'Короткозамыкатель','OTYP_SHORTING_SWITCH');
insert into equipment_type (id,name,alias) values (43,'Автотрансформатор трехобмоточный','OTYP_THREE_WINDING_AUTOTRANS');
insert into equipment_type (id,name,alias) values (44,'Трансформатор напряжения','OTYP_VOLTAGE_TRANSFORMER');
insert into equipment_type (id,name,alias) values (45,'Сегмент воздушной линии','OTYP_AIR_LINE_SEGMENT');
insert into equipment_type (id,name,alias) values (46,'Автомат','OTYP_AUTOMATIC_SWITCH');
insert into equipment_type (id,name,alias) values (47,'Сегмент кабельной линии','OTYP_CABLE_LINE_SEGMENT');
insert into equipment_type (id,name,alias) values (48,'Ошиновка','OTYP_LEAD');
insert into equipment_type (id,name,alias) values (49,'Дроссельная катушка','OTYP_CHOKE_COIL');
insert into equipment_type (id,name,alias) values (50,'Турбогенератор','OTYP_TURBOGENERATOR');
insert into equipment_type (id,name,alias) values (51,'Трансформатор тока','OTYP_CURRENT_TRANSFORMER');
insert into equipment_type (id,name,alias) values (52,'Реактор одинарный','OTYP_SINGLE_REACTOR');
insert into equipment_type (id,name,alias) values (53,'Ветвь реактора','OTYP_REACTOR_BRANCH');
insert into equipment_type (id,name,alias) values (54,'Индикатор КЗ','OTYP_IKZ');
insert into equipment_type (id,name,alias) values (55,'Опора','OTYP_SUPPORT');
